#define ENCODER_A_PINS { GP28 }
#define ENCODER_B_PINS { GP29 }

#define ENCODER_RESOLUTION 4
#define ENCODER_DIRECTION_FLIP

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_TIMEOUT 80000

#define WS2812_DI_PIN GP12
#define RGBLIGHT_LED_COUNT 1

#define RGBLIGHT_EFFECT_RAINBOW_SWIRL	
#define RGBLIGHT_DEFAULT_VAL 80
