#define ENCODER_A_PINS { GP28 }
#define ENCODER_B_PINS { GP29 }
#define ENCODER_DIRECTION_FLIP

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_TIMEOUT 1200000
