name: Build Vial firmware

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip gcc-avr binutils-avr avr-libc dfu-programmer dfu-util unzip wget git make
          pip3 install pillow

      - name: Build firmware
        run: |
          make ahnaf/idkpad:vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: idkpad-firmware
          path: |
            *.bin
            *.hex
