name: Build Vial firmware

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Init QMK submodules
        run: |
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip gcc-avr binutils-avr avr-libc dfu-programmer dfu-util unzip wget git make
          pip3 install pillow

      - name: Build firmware
        run: |
          make idkpad:vial

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          name: idkpad-firmware
          path: '*.bin'
