name: Build Vial firmware

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout keymap repo
        uses: actions/checkout@v4

      - name: Checkout QMK firmware
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          path: qmk_firmware

      - name: Copy keymap into QMK
        run: |
          mkdir -p qmk_firmware/keyboards/ahnaf/idkpad/keymaps/vial
          cp keymaps/vial/* qmk_firmware/keyboards/ahnaf/idkpad/keymaps/vial/

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip gcc-avr binutils-avr avr-libc dfu-programmer dfu-util unzip wget git make
          pip3 install pillow

      - name: Build firmware
        working-directory: qmk_firmware
        run: |
          make ahnaf/idkpad:vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: idkpad-firmware
          path: qmk_firmware/*.hex
